-- MySQL Script generated by MySQL Workbench
-- Thu Aug  8 20:10:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema book_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `book_db` ;

-- -----------------------------------------------------
-- Schema book_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `book_db` DEFAULT CHARACTER SET utf8 ;
USE `book_db` ;

-- -----------------------------------------------------
-- Table `book_db`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `book_db`.`books` ;

CREATE TABLE IF NOT EXISTS `book_db`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NULL,
  `year` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS book_admin;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'book_admin' IDENTIFIED BY 'book_admin';

GRANT ALL ON `book_db`.* TO 'book_admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
